-- ============================================================
-- 006_archive_replace_transactions.sql
-- Phase 2.1 — Archive old transactions, create new schema
--
-- Old transactions schema (from apps/qr/sql/004_create_transactions.sql):
--   id, nomor_seri, type (masuk/keluar), quantity, operator, notes, created_at
--
-- New transactions schema:
--   transaction_id (UUID PK), transaction_code, client_id, source_branch_id,
--   destination_branch_id, transaction_type (sale/purchase/return/transfer),
--   status, financials, created_by, approved_by, approved_at
--
-- Strategy:
--   Step A: Archive old table as _old_transactions
--   Step B: Create new transactions table from scratch
--   Step C: (Optional) Manual data migration from _old_transactions
--
-- NOTE: Old data in transactions is NOT automatically migrated because
--       the schema is fundamentally different (masuk/keluar → sale/purchase/transfer/return).
--       Manual review required to migrate historical data.
-- ============================================================

BEGIN;

-- ── STEP 6a: Archive old transactions table ───────────────────────────────────
-- Rename instead of drop — preserves historical data for manual review
ALTER TABLE IF EXISTS transactions
  RENAME TO _old_transactions;

-- ── STEP 6b: Create new transactions table ────────────────────────────────────
CREATE TABLE transactions (
  -- Primary Key
  transaction_id        UUID        PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable code (e.g. TRX-20260608-0001)
  -- Auto-generated by application layer
  transaction_code      TEXT        NOT NULL UNIQUE,

  -- Parties
  client_id             UUID        REFERENCES clients(client_id)  ON DELETE RESTRICT,
  source_branch_id      UUID        REFERENCES branches(branch_id) ON DELETE RESTRICT,
  destination_branch_id UUID        REFERENCES branches(branch_id) ON DELETE RESTRICT,

  -- Type & Status
  transaction_type      TEXT        NOT NULL
                        CHECK (transaction_type IN ('sale', 'purchase', 'return', 'transfer')),
  status                TEXT        NOT NULL DEFAULT 'draft'
                        CHECK (status IN ('draft', 'pending', 'completed', 'cancelled')),

  -- Financials (all in IDR)
  subtotal              NUMERIC(15,2) NOT NULL DEFAULT 0,
  discount_amount       NUMERIC(15,2) NOT NULL DEFAULT 0,
  tax_amount            NUMERIC(15,2) NOT NULL DEFAULT 0,
  shipping_cost         NUMERIC(15,2) NOT NULL DEFAULT 0,
  grand_total           NUMERIC(15,2) NOT NULL DEFAULT 0,

  -- Operational
  notes                 TEXT,
  transaction_date      DATE        NOT NULL DEFAULT CURRENT_DATE,

  -- Audit Trail
  created_by            UUID        REFERENCES admins(id) ON DELETE SET NULL,
  approved_by           UUID        REFERENCES admins(id) ON DELETE SET NULL,
  approved_at           TIMESTAMPTZ,     -- set when status changes to completed/cancelled

  -- System
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── STEP 6c: Branch validation per transaction_type ──────────────────────────
-- These are documented business rules enforced at application layer (not DB),
-- because PostgreSQL CHECK constraints cannot reference other column values
-- in a flexible cross-type way without complex triggers.
--
-- sale:     source_branch_id REQUIRED,  destination_branch_id OPTIONAL
-- purchase: source_branch_id OPTIONAL,  destination_branch_id REQUIRED
-- transfer: source_branch_id REQUIRED,  destination_branch_id REQUIRED
-- return:   source_branch_id OPTIONAL,  destination_branch_id REQUIRED

-- ── STEP 6d: Comments ─────────────────────────────────────────────────────────
COMMENT ON TABLE transactions IS 'Transaction headers. Items in transaction_items. Old schema archived in _old_transactions.';
COMMENT ON COLUMN transactions.transaction_code IS 'Human-readable code. Format: TRX-YYYYMMDD-NNNN. Generated by app service.';
COMMENT ON COLUMN transactions.source_branch_id IS 'Branch where asset moves FROM. Required for sale and transfer.';
COMMENT ON COLUMN transactions.destination_branch_id IS 'Branch where asset moves TO. Required for purchase, return, transfer.';
COMMENT ON COLUMN transactions.approved_at IS 'Timestamp when status changed to completed or cancelled. NULL if still in draft/pending.';
COMMENT ON COLUMN transactions.grand_total IS 'Validated by app layer: subtotal - discount_amount + tax_amount + shipping_cost.';

-- ── STEP 6e: RLS ──────────────────────────────────────────────────────────────
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read transactions
CREATE POLICY "transactions_select_authenticated"
  ON transactions FOR SELECT
  TO authenticated
  USING (true);

-- All authenticated users can create draft transactions
CREATE POLICY "transactions_insert_authenticated"
  ON transactions FOR INSERT
  TO authenticated
  WITH CHECK (status = 'draft');

-- Only admins can update transactions
CREATE POLICY "transactions_update_admin"
  ON transactions FOR UPDATE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM admins
      WHERE id = auth.uid()
        AND role IN ('super_admin', 'admin')
        AND deleted_at IS NULL
    )
  );

-- Warehouse can update their own draft transactions
CREATE POLICY "transactions_update_own_draft"
  ON transactions FOR UPDATE
  TO authenticated
  USING (
    created_by = auth.uid()
    AND status = 'draft'
  );

COMMIT;

-- ── Manual Data Migration (OPTIONAL) ─────────────────────────────────────────
-- Review _old_transactions and migrate relevant data manually.
-- Old schema: id, nomor_seri, type (masuk/keluar), quantity, operator, notes, created_at
--
-- Example: migrate 'masuk' → purchase transactions
-- (Requires manual mapping — do NOT auto-run this)
--
-- INSERT INTO transactions (transaction_code, transaction_type, status, notes, created_at)
-- SELECT
--   'LEGACY-' || id,
--   CASE WHEN type = 'masuk' THEN 'purchase' ELSE 'sale' END,
--   'completed',
--   'Migrated from legacy: ' || COALESCE(notes, ''),
--   created_at
-- FROM _old_transactions;
