import { supabase } from '@/lib/supabase'
import type { TransactionRow, TransactionInsert, TransactionUpdate, TransactionItemRow, TransactionItemInsert, TransactionStatsRow } from '@/types/database'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface GetTransactionsParams {
  status?: TransactionRow['status']
  transaction_type?: TransactionRow['transaction_type']
  client_id?: string
  branch_id?: string
  limit?: number
  offset?: number
}

export interface TransactionStats {
  total_count: number
  completed_count: number
  pending_count: number
  draft_count: number
  total_revenue: number
}

export interface TransactionTrendDatum {
  date: string      // YYYY-MM-DD
  count: number
  revenue: number
}

export interface TransactionWithRelations extends TransactionRow {
  client?: { customer_name: string } | null
  source_branch?: { branch_name: string } | null
  destination_branch?: { branch_name: string } | null
}

export interface TransactionWithItems extends TransactionWithRelations {
  items: TransactionItemRow[]
}

// ─── Service ──────────────────────────────────────────────────────────────────

export const transactionsService = {

  /**
   * Fetch transactions list with optional filters.
   */
  async getTransactions(params: GetTransactionsParams = {}): Promise<TransactionWithRelations[]> {
    const { status, transaction_type, client_id, branch_id, limit = 50, offset = 0 } = params

    let query = supabase
      .from('transactions')
      .select('*, client:clients(customer_name), source_branch:branches!source_branch_id(branch_name), destination_branch:branches!destination_branch_id(branch_name)')
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1)

    if (status) query = query.eq('status', status)
    if (transaction_type) query = query.eq('transaction_type', transaction_type)
    if (client_id) query = query.eq('client_id', client_id)
    if (branch_id) {
      query = query.or(`source_branch_id.eq.${branch_id},destination_branch_id.eq.${branch_id}`)
    }

    const { data, error } = await query
    if (error) throw new Error(`Failed to fetch transactions: ${error.message}`)
    return data ?? []
  },

  /**
   * Fetch single transaction with its items.
   */
  async getTransactionWithItems(transaction_id: string): Promise<TransactionWithItems | null> {
    const { data: txn, error: txnError } = await supabase
      .from('transactions')
      .select('*')
      .eq('transaction_id', transaction_id)
      .single()

    if (txnError && txnError.code !== 'PGRST116') {
      throw new Error(`Failed to fetch transaction: ${txnError.message}`)
    }
    if (!txn) return null

    const { data: items, error: itemsError } = await supabase
      .from('transaction_items')
      .select('*')
      .eq('transaction_id', transaction_id)
      .order('created_at', { ascending: true })

    if (itemsError) throw new Error(`Failed to fetch transaction items: ${itemsError.message}`)

    return { ...txn, items: items ?? [] }
  },

  /**
   * Create a new transaction in draft status.
   * transaction_code is auto-generated by the DB function generate_transaction_code().
   * Do NOT pass transaction_code from the client.
   */
  async createTransaction(data: Omit<TransactionInsert, 'transaction_code'>): Promise<TransactionRow> {
    const { data: created, error } = await supabase
      .from('transactions')
      .insert({ ...data, status: 'draft' })
      .select()
      .single()

    if (error) throw new Error(`Failed to create transaction: ${error.message}`)
    if (!created) throw new Error('Transaction creation returned no data')
    return created
  },

  /**
   * Add items to a draft/pending transaction.
   */
  async addTransactionItems(items: TransactionItemInsert[]): Promise<TransactionItemRow[]> {
    const { data, error } = await supabase
      .from('transaction_items')
      .insert(items)
      .select()

    if (error) throw new Error(`Failed to add transaction items: ${error.message}`)
    return data ?? []
  },

  /**
   * Submit a draft transaction (draft → pending).
   * Only the creator or admins can submit.
   */
  async submitTransaction(transaction_id: string): Promise<TransactionRow> {
    const { data, error } = await supabase
      .from('transactions')
      .update({
        status: 'pending',
        updated_at: new Date().toISOString(),
      } as any)
      .eq('transaction_id', transaction_id)
      .eq('status', 'draft')
      .select()
      .single()

    if (error) throw new Error(`Failed to submit transaction: ${error.message}`)
    if (!data) throw new Error('Transaction not found or not in draft status')
    return data
  },

  /**
   * Update transaction fields (only draft/pending transactions).
   */
  async updateTransaction(transaction_id: string, data: TransactionUpdate): Promise<TransactionRow> {
    const { data: updated, error } = await supabase
      .from('transactions')
      .update({ ...data, updated_at: new Date().toISOString() } as any)
      .eq('transaction_id', transaction_id)
      .select()
      .single()

    if (error) throw new Error(`Failed to update transaction: ${error.message}`)
    if (!updated) throw new Error('Transaction update returned no data')
    return updated
  },

  /**
   * Get aggregate stats for dashboard metric cards.
   * Reads from the server-side `transaction_stats` VIEW (012_create_stats_views.sql).
   * Replaces the old client-side reduce over all rows — O(1) network payload.
   */
  async getTransactionStats(): Promise<TransactionStats> {
    const { data, error } = await supabase
      .from('transaction_stats' as any)
      .select('*')
      .single()

    if (error) throw new Error(`Failed to fetch transaction stats: ${error.message}`)

    const stats = data as unknown as TransactionStatsRow | null

    return {
      total_count: Number(stats?.total_count ?? 0),
      completed_count: Number(stats?.completed_count ?? 0),
      pending_count: Number(stats?.pending_count ?? 0),
      draft_count: Number(stats?.draft_count ?? 0),
      total_revenue: Number(stats?.total_revenue ?? 0),
    }
  },

  /**
   * Get daily transaction trend for area chart.
   * Returns count and revenue per day for the last N days.
   */
  async getTransactionTrend(days: number): Promise<TransactionTrendDatum[]> {
    const since = new Date()
    since.setDate(since.getDate() - days)

    const { data, error } = await supabase
      .from('transactions')
      .select('transaction_date, grand_total')
      .eq('status', 'completed')
      .gte('transaction_date', since.toISOString().split('T')[0])
      .order('transaction_date', { ascending: true })

    if (error) throw new Error(`Failed to fetch transaction trend: ${error.message}`)

    // Aggregate by date
    const map = new Map<string, { count: number; revenue: number }>()
    for (const row of data ?? []) {
      const date = row.transaction_date
      const existing = map.get(date) ?? { count: 0, revenue: 0 }
      map.set(date, {
        count: existing.count + 1,
        revenue: existing.revenue + (row.grand_total ?? 0),
      })
    }

    // Fill missing dates with 0s
    const result: TransactionTrendDatum[] = []
    for (let i = days; i >= 0; i--) {
      const d = new Date()
      d.setDate(d.getDate() - i)
      const date = d.toISOString().split('T')[0]
      const entry = map.get(date) ?? { count: 0, revenue: 0 }
      result.push({ date, ...entry })
    }

    return result
  },

  /**
   * Fetch recent transactions for dashboard table.
   */
  async getRecentTransactions(limit = 10): Promise<TransactionWithRelations[]> {
    const { data, error } = await supabase
      .from('transactions')
      .select('*, client:clients(customer_name), source_branch:branches!source_branch_id(branch_name), destination_branch:branches!destination_branch_id(branch_name)')
      .order('created_at', { ascending: false })
      .limit(limit)

    if (error) throw new Error(`Failed to fetch recent transactions: ${error.message}`)
    return data ?? []
  },

  /**
   * Approve a pending transaction.
   * Calls the server-side Postgres function approve_transaction().
   * Validates: admin role, no self-approval, advisory lock on products.
   * Generates inventory_movements and updates product state atomically.
   */
  async approveTransaction(transaction_id: string): Promise<TransactionRow> {
    const { data, error } = await (supabase as any)
      .rpc('approve_transaction', { p_transaction_id: transaction_id })

    if (error) throw new Error(`Failed to approve transaction: ${error.message}`)
    if (!data) throw new Error('Approval returned no data')
    return data as TransactionRow
  },

  /**
   * Cancel a draft or pending transaction.
   * Calls the server-side Postgres function cancel_transaction().
   * Warehouse can cancel own drafts; admin/super_admin can cancel any draft or pending.
   */
  async cancelTransaction(transaction_id: string, reason?: string): Promise<TransactionRow> {
    const { data, error } = await (supabase as any)
      .rpc('cancel_transaction', {
        p_transaction_id: transaction_id,
        p_reason: reason ?? null,
      })

    if (error) throw new Error(`Failed to cancel transaction: ${error.message}`)
    if (!data) throw new Error('Cancellation returned no data')
    return data as TransactionRow
  },
}
