import React,{useState} from 'react';
import CropModal from './CropModal';

function Field({label,value,onChange,placeholder=''}){return <label className="field"><span>{label}</span><input value={value||''} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function TextArea({label,value,onChange}){return <label className="field"><span>{label}</span><textarea value={value||''} onChange={e=>onChange(e.target.value)}/></label>}

export default function Form({data,setData,step,setStep}){
 const [crop,setCrop]=useState(null);
 const update=(k,v)=>setData(d=>({...d,[k]:v}));
 const upProd=(i,k,v)=>setData(d=>({...d,products:d.products.map((p,n)=>n===i?{...p,[k]:v}:p)}));
 const addPhoto=(i,type,file)=>{if(file)setCrop({src:URL.createObjectURL(file),i,type});};
 const steps=['Cover & Identitas','Produk & Foto','Temuan Survey','Solusi','Review'];
 return <section className="builder">
   <div className="stepper">{steps.map((s,i)=><button className={i===step?'active':''} onClick={()=>setStep(i)} key={s}><b>{i+1}</b>{s}</button>)}</div>
   {step===0&&<div className="panel"><h2>Cover &amp; identitas</h2><div className="grid2"><Field label="Judul laporan" value={data.coverTitle} onChange={v=>update('coverTitle',v)}/><Field label="Nama client" value={data.clientName} onChange={v=>update('clientName',v)}/><Field label="Subjudul" value={data.coverSubtitle} onChange={v=>update('coverSubtitle',v)}/><Field label="Tanggal survey" value={data.surveyDate} onChange={v=>update('surveyDate',v)}/><Field label="Lokasi survey" value={data.surveyLocation} onChange={v=>update('surveyLocation',v)}/><Field label="Jenis report" value={data.reportType==='final'?'Final Survey':'Survey'} onChange={v=>update('reportType',v.toLowerCase().includes('final')?'final':'survey')}/></div><TextArea label="Alamat client" value={data.address} onChange={v=>update('address',v)}/><div className="upload-row"><div><b>Logo client</b><p className="muted">Upload logo client. Crop mempertahankan rasio area cover.</p></div><input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)setCrop({src:URL.createObjectURL(f),type:'logo'})}}/><img className="logo-thumb" src={data.clientLogo} /></div></div>}
   {step===1&&<div className="panel"><div className="panel-title"><div><h2>Produk survey</h2><p className="muted">Satu produk menghasilkan dua halaman. Foto diperlakukan sebagai potret 3:4.</p></div><button className="primary" onClick={()=>setData(d=>({...d,products:[...d.products,{...d.products[0],name:'Produk Baru',photos:[],measurementPhotos:[]}]}))}>+ Tambah produk</button></div>{data.products.map((p,i)=><div className="product-card" key={i}><div className="product-head"><h3>Produk {i+1}</h3><button className="danger" disabled={data.products.length===1} onClick={()=>setData(d=>({...d,products:d.products.filter((_,n)=>n!==i)}))}>Hapus</button></div><div className="grid3"><Field label="Nama perangkat" value={p.name} onChange={v=>upProd(i,'name',v)}/><Field label="Brand" value={p.brand} onChange={v=>upProd(i,'brand',v)}/><Field label="Kapasitas" value={p.capacity} onChange={v=>upProd(i,'capacity',v)}/><Field label="Phase R" value={p.phaseR} onChange={v=>upProd(i,'phaseR',v)}/><Field label="Phase S" value={p.phaseS} onChange={v=>upProd(i,'phaseS',v)}/><Field label="Phase T" value={p.phaseT} onChange={v=>upProd(i,'phaseT',v)}/><Field label="Voltage" value={p.voltage} onChange={v=>upProd(i,'voltage',v)}/><Field label="Grounding" value={p.grounding} onChange={v=>upProd(i,'grounding',v)}/><Field label="UPS" value={p.ups} onChange={v=>upProd(i,'ups',v)}/><Field label="Stabilizer" value={p.stabilizer} onChange={v=>upProd(i,'stabilizer',v)}/><Field label="Proteksi power" value={p.powerProtection} onChange={v=>upProd(i,'powerProtection',v)}/><Field label="Proteksi komunikasi" value={p.communicationProtection} onChange={v=>upProd(i,'communicationProtection',v)}/><Field label="Load" value={p.load} onChange={v=>upProd(i,'load',v)}/></div><TextArea label="Catatan" value={p.note} onChange={v=>upProd(i,'note',v)}/><PhotoUploader title="Foto perangkat / Phase" photos={p.photos} onAdd={f=>addPhoto(i,'photos',f)} onRemove={n=>upProd(i,'photos',p.photos.filter((_,k)=>k!==n))}/><PhotoUploader title="Foto pengukuran" photos={p.measurementPhotos} onAdd={f=>addPhoto(i,'measurementPhotos',f)} onRemove={n=>upProd(i,'measurementPhotos',p.measurementPhotos.filter((_,k)=>k!==n))}/></div>)}</div>}
   {step===2&&<div className="panel"><h2>Kondisi hasil survey</h2>{data.findings.map((x,i)=><div className="row-input" key={i}><textarea value={x} onChange={e=>update('findings',data.findings.map((v,n)=>n===i?e.target.value:v))}/><button onClick={()=>update('findings',data.findings.filter((_,n)=>n!==i))}>×</button></div>)}<button onClick={()=>update('findings',[...data.findings,''])}>+ Tambah temuan</button></div>}
   {step===3&&<div className="panel"><h2>Design solusi yang dibutuhkan</h2>{data.requiredSolution.map((x,i)=><div className="row-input" key={i}><textarea value={x} onChange={e=>update('requiredSolution',data.requiredSolution.map((v,n)=>n===i?e.target.value:v))}/><button onClick={()=>update('requiredSolution',data.requiredSolution.filter((_,n)=>n!==i))}>×</button></div>)}<button onClick={()=>update('requiredSolution',[...data.requiredSolution,''])}>+ Tambah poin</button><hr/><TextArea label="Penjelasan gambar" value={data.explanation} onChange={v=>update('explanation',v)}/></div>}
   {step===4&&<div className="panel"><h2>Review &amp; Finalisasi</h2><p>Preview di bawah adalah dokumen yang akan dirender. Halaman template tetap terkunci. Tombol Unduh PDF berada di toolbar preview.</p><div className="review-grid"><div><b>Produk</b><strong>{data.products.length}</strong></div><div><b>Foto</b><strong>{data.products.reduce((a,p)=>a+p.photos.length+p.measurementPhotos.length,0)}</strong></div><div><b>Temuan</b><strong>{data.findings.length}</strong></div></div></div>}
   {crop&&<CropModal src={crop.src} ratio={crop.type==='logo'?1:3/4} onClose={()=>setCrop(null)} onSave={url=>{if(crop.type==='logo')update('clientLogo',url);else setData(d=>({...d,products:d.products.map((p,n)=>n===crop.i?{...p,[crop.type]:[...p[crop.type],url]}:p)}));setCrop(null)}}/>}
 </section>
}
function PhotoUploader({title,photos,onAdd,onRemove}){return <div className="photo-input"><div><b>{title}</b><p className="muted">Rasio crop 3:4 (potret). Jumlah foto boleh kurang dari slot template.</p></div><div className="photo-strip">{photos.map((src,n)=><div className="photo-chip" key={n}><img src={(/^(?:data:|blob:|https?:|\/)/).test(src)?src:`/report-assets/${src}`} /><button onClick={()=>onRemove(n)}>×</button></div>)}<label className="add-photo">+<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)onAdd(f);e.target.value=''}}/></label></div></div>}
