-- ============================================================
-- 008_create_inventory_movements.sql
-- Phase 2.1 — Create inventory_movements table
--
-- Purpose: Complete audit trail of every asset movement.
--
-- Generation rules:
--   - AUTO-generated by application service layer when transaction approved:
--       purchase  → 1 row (stock_in  at destination_branch_id)
--       sale      → 1 row (stock_out from source_branch_id)
--       transfer  → 2 rows (stock_out from source + stock_in to destination)
--       return    → 1 row (stock_in  at destination_branch_id)
--   - MANUAL-only by super_admin/admin:
--       adjustment → 1 row, transaction_id = NULL, notes REQUIRED
--
-- MUST run AFTER 006 and 007.
-- ============================================================

BEGIN;

CREATE TABLE inventory_movements (
  -- Primary Key
  movement_id       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Asset (RESTRICT: cannot delete product if movements exist)
  product_id        UUID          NOT NULL
                    REFERENCES products(product_id) ON DELETE RESTRICT,

  -- Branch context (SET NULL: movement log survives branch soft-delete)
  branch_id         UUID
                    REFERENCES branches(branch_id) ON DELETE SET NULL,

  -- Linked transaction (SET NULL: log survives even if transaction is archived)
  -- NULL for manual adjustment movements
  transaction_id    UUID
                    REFERENCES transactions(transaction_id) ON DELETE SET NULL,

  -- Movement type
  movement_type     TEXT          NOT NULL
                    CHECK (movement_type IN (
                      'stock_in',    -- asset received at branch
                      'stock_out',   -- asset dispatched from branch
                      'transfer',    -- internal (use stock_out + stock_in pair instead)
                      'return',      -- asset returned from client
                      'adjustment'   -- manual correction by super_admin/admin
                    )),

  -- Quantity tracking
  -- For serial-number assets, values are always 0 or 1.
  -- Retained for forward compatibility (consumables/spare parts).
  quantity_before   INTEGER       NOT NULL,
  quantity_change   INTEGER       NOT NULL,  -- positive = in, negative = out
  quantity_after    INTEGER       NOT NULL,

  -- Operational
  -- REQUIRED for 'adjustment' movement_type (enforced at application layer)
  notes             TEXT,

  -- Audit
  created_by        UUID          REFERENCES admins(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ   NOT NULL DEFAULT NOW()
  -- No updated_at: movements are append-only / immutable after creation
);

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE inventory_movements IS 'Append-only audit trail of every asset movement. Never update or delete rows.';
COMMENT ON COLUMN inventory_movements.branch_id IS 'Which branch this movement belongs to. For transfer: 2 rows (source + destination) each with their own branch_id.';
COMMENT ON COLUMN inventory_movements.transaction_id IS 'Linked transaction. NULL for manual adjustments.';
COMMENT ON COLUMN inventory_movements.movement_type IS 'stock_in/stock_out for purchase/sale/return. transfer is deprecated (use stock_out+stock_in pair). adjustment = manual by admin.';
COMMENT ON COLUMN inventory_movements.quantity_change IS 'Positive = asset arrived. Negative = asset departed. For serial assets: always +1 or -1.';
COMMENT ON COLUMN inventory_movements.notes IS 'Required for adjustment movements. Documents reason for manual correction.';

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;

-- All authenticated users can read movements
CREATE POLICY "inv_mov_select_authenticated"
  ON inventory_movements FOR SELECT
  TO authenticated
  USING (true);

-- Only application service inserts movements (authenticated context)
CREATE POLICY "inv_mov_insert_authenticated"
  ON inventory_movements FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- No UPDATE or DELETE on inventory_movements — append-only.
-- If a mistake was made, create an 'adjustment' movement to correct it.

COMMIT;
